# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/main_parsingPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowParsing(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1250, 10, 231, 91))
        self.label_2.setStyleSheet("font: 30pt \"DejaVu Sans\"; color:rgb(174,0,0)")
        self.label_2.setObjectName("label_2")
        self.tableStaff = QtWidgets.QTableWidget(self.centralwidget)
        self.tableStaff.setGeometry(QtCore.QRect(670, 270, 881, 521))
        self.tableStaff.setStyleSheet("font: 8pt \"DejaVu Sans\";")
        self.tableStaff.setObjectName("tableStaff")
        self.tableStaff.setColumnCount(5)
        self.tableStaff.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableStaff.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStaff.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStaff.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStaff.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStaff.setHorizontalHeaderItem(4, item)
        self.ph_errors = QtWidgets.QPushButton(self.centralwidget)
        self.ph_errors.setGeometry(QtCore.QRect(1000, 130, 201, 51))
        self.ph_errors.setStyleSheet("border-radius:20px;\n"
"font: 12pt \"DejaVu Sans\";color:rgb(255, 255, 255);\n"
"background-color:rgb(174,0,0);")
        self.ph_errors.setObjectName("ph_errors")
        self.tableAbs = QtWidgets.QTableWidget(self.centralwidget)
        self.tableAbs.setGeometry(QtCore.QRect(10, 270, 651, 521))
        self.tableAbs.setStyleSheet("font: 8pt \"DejaVu Sans\";")
        self.tableAbs.setObjectName("tableAbs")
        self.tableAbs.setColumnCount(5)
        self.tableAbs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableAbs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAbs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAbs.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAbs.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAbs.setHorizontalHeaderItem(4, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 10, 231, 91))
        self.label.setStyleSheet("font: 30pt \"DejaVu Sans\"; color:rgb(174,0,0)")
        self.label.setObjectName("label")
        self.cb_birim = QtWidgets.QComboBox(self.centralwidget)
        self.cb_birim.setGeometry(QtCore.QRect(30, 140, 231, 27))
        self.cb_birim.setObjectName("cb_birim")
        self.ph_display = QtWidgets.QPushButton(self.centralwidget)
        self.ph_display.setGeometry(QtCore.QRect(560, 130, 201, 51))
        self.ph_display.setStyleSheet("border-radius:20px;\n"
"font: 12pt \"DejaVu Sans\";color:rgb(255, 255, 255);\n"
"background-color:rgb(174,0,0);")
        self.ph_display.setObjectName("ph_display")
        self.cb_bolum = QtWidgets.QComboBox(self.centralwidget)
        self.cb_bolum.setGeometry(QtCore.QRect(280, 140, 231, 27))
        self.cb_bolum.setObjectName("cb_bolum")
        self.ph_difference = QtWidgets.QPushButton(self.centralwidget)
        self.ph_difference.setGeometry(QtCore.QRect(780, 130, 201, 51))
        self.ph_difference.setStyleSheet("border-radius:20px;\n"
"font: 12pt \"DejaVu Sans\";color:rgb(255, 255, 255);\n"
"background-color:rgb(174,0,0);")
        self.ph_difference.setObjectName("ph_difference")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Staff Api"))
        item = self.tableStaff.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Unvan"))
        item = self.tableStaff.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "İsim"))
        item = self.tableStaff.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Bölüm"))
        item = self.tableStaff.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Birim"))
        item = self.tableStaff.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Dahili"))
        self.ph_errors.setText(_translate("MainWindow", "Errors"))
        item = self.tableAbs.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Avatar"))
        item = self.tableAbs.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Unvan"))
        item = self.tableAbs.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "İsim"))
        item = self.tableAbs.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Bölüm"))
        item = self.tableAbs.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Birim"))
        self.label.setText(_translate("MainWindow", "Abs Api"))
        self.ph_display.setText(_translate("MainWindow", "Display"))
        self.ph_difference.setText(_translate("MainWindow", "Difference"))
