# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/main_personWho.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowPersonWho(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(420, 340, 79, 19))
        self.label_4.setObjectName("label_4")
        self.ln_uluslararasiMakale = QtWidgets.QLineEdit(self.centralwidget)
        self.ln_uluslararasiMakale.setGeometry(QtCore.QRect(610, 160, 131, 27))
        self.ln_uluslararasiMakale.setObjectName("ln_uluslararasiMakale")
        self.ln_kitap = QtWidgets.QLineEdit(self.centralwidget)
        self.ln_kitap.setGeometry(QtCore.QRect(610, 280, 131, 27))
        self.ln_kitap.setObjectName("ln_kitap")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 220, 151, 19))
        self.label_2.setObjectName("label_2")
        self.ln_ulusalMakale = QtWidgets.QLineEdit(self.centralwidget)
        self.ln_ulusalMakale.setGeometry(QtCore.QRect(610, 220, 131, 27))
        self.ln_ulusalMakale.setObjectName("ln_ulusalMakale")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 160, 181, 19))
        self.label.setObjectName("label")
        self.ph_who = QtWidgets.QPushButton(self.centralwidget)
        self.ph_who.setGeometry(QtCore.QRect(500, 420, 171, 51))
        self.ph_who.setStyleSheet("border-radius:20px;\n"
"font: 12pt \"DejaVu Sans\";color:rgb(255, 255, 255);\n"
"background-color:rgb(174,0,0);")
        self.ph_who.setObjectName("ph_who")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 280, 79, 19))
        self.label_3.setObjectName("label_3")
        self.ln_bildiri = QtWidgets.QLineEdit(self.centralwidget)
        self.ln_bildiri.setGeometry(QtCore.QRect(610, 340, 131, 27))
        self.ln_bildiri.setObjectName("ln_bildiri")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Bidiri"))
        self.label_2.setText(_translate("MainWindow", "Ulusal Makale"))
        self.label.setText(_translate("MainWindow", "Uluslararası Makale"))
        self.ph_who.setText(_translate("MainWindow", "WHO"))
        self.label_3.setText(_translate("MainWindow", "Kitap"))
